In [34]:
import pandas as pd
from pathlib import Path
import yaml

In [35]:
configs = yaml.safe_load(Path("../config.yaml").read_text())

In [36]:
configs

{'chunking': {'chunk_size': 300, 'chunk_overlap': 50},
 'models': {'embedding': 'intfloat/multilingual-e5-large',
  'reranker': 'BAAI/bge-reranker-v2-m3'},
 'search': {'top_k': 10,
  'rerank_candidates': 50,
  'rrf_k': 60,
  'aggregation': 'max'},
 'paths': {'raw': 'data/candidate_public/candidate_data/articles.f',
  'calibration_raw': 'data/candidate_public/candidate_data/calibration.f',
  'test': 'data/candidate_public/candidate_data/test.f',
  'reports': 'reports/reports.md',
  'calibration': 'data/queries.jsonl'}}

In [39]:
df = pd.read_feather("../" + configs["paths"]["raw"])
calibration = pd.read_feather("../" + configs['paths']["calibration_raw"])
test = pd.read_feather("../" + configs["paths"]["test"])

/home/dmitriy/projects/avito-rag-search/.venv/lib/python3.14/site-packages/pandas/io/feather_format.py:178: FutureWarning: pyarrow.feather.read_table is deprecated as of 24.0.0. Use pyarrow.ipc.open_file() / RecordBatchFileReader instead. Feather V2 is the Arrow IPC file format.
  pa_table = feather.read_table(

In [40]:
df

,article_id,title,body
0,1730,Имя или название компании,"<ol><li><p>Зайдите в раздел <a href=""https://w..."
1,1746,"Понять, что профиль заблокирован","<p>Проверьте, какое сообщение вы видите при вх..."
2,1747,Не допустить блокировки профиля,<ol><li><p><strong>Не заводите несколько аккау...
3,1774,Оставить или удалить профиль,<p>⚡ Не удаляйте профиль с подтверждёнными дан...
4,1775,Удалить профиль,"<p>⚡ Удалить профиль не получится, если у вас ..."
...,...,...,...
788,4545,Лента постов от продавца,<p>Теперь на Авито можно публиковать не только...
789,4547,Записаться на тест-драйв,<p>Записаться на тест-драйв</p>
790,4548,Автоматический чат с продавцом,"<p>Иногда покупатель интересуется объявлением,..."
791,4549,Автоматический чат с продавцом,"<p>Иногда покупатель интересуется объявлением,..."
792,4551,Неверный параметр в Товарах,<p><strong>Почему отклонили</strong>: Параметр...

In [41]:
df['article_id'].nunique() == df['article_id'].count()

np.True_

In [42]:
calibration

     query_id                                         query_text ground_truth
0           1              Как передать товар через службу авито    1909 4234
1           2  Можете подсказать, если заказать товар Авито д...    2865 4400
2           3     Здравствуйте. Как отправить товар через Авито.         1909
3           4  как получить деньги за возрат если продавец уж...    4400 4403
4           5  Когда мне прийдут деньги за доставку, сегодня ...         4361
..        ...                                                ...          ...
495       496  Хочу закрыть кошелек и чтобы деньги за продажи...         4384
496       497             Сколько платит покупатель за доставку?    1951 4234
497       498                   Почему нету доставки за <MONEY>?    1951 4234
498       499  Добрый вечер 🌇 Присылали промокод на <MONEY> н...    2665 4214
499       500          Почему не могу списать бонусы при покупке    2646 4219

[500 rows x 3 columns]

In [43]:
test

     query_id                                         query_text
0           1  Здравствуйте! Подскажите, пожалуйста, не могу ...
1           2  Здравствуйте , почему так долго доставляется в...
2           3  Здравствуйте,подскажите как мне отправить крос...
3           4  Здравствуйте! В каких случаях за возврат снима...
4           5  Почему у меня доставки в несколько раз дороже ...
..        ...                                                ...
495       496  Отправила заказ авито доставкой . Куда не вижу...
496       497  Добрый вечер , мой заказ потерян, могу ли я по...
497       498              Не пришли деньги за товар. Что делать
498       499  Как добавить бесплатную доставку в уже активно...
499       500  Здравствуйте. Как я могу отключить опцию лично...

[500 rows x 2 columns]

In [48]:
df['body'].iloc[1]

'<p>Проверьте, какое сообщение вы видите при входе в профиль.</p><div class="tabset tabset_155"><input type="radio" name="tab_radio_155" id="set155_tab1" class="tab-radio" checked><label for="set155_tab1" class="tab-label" data-tab-name="1"><p>Профиль заблокирован</p></label><input type="radio" name="tab_radio_155" id="set155_tab2" class="tab-radio"><label for="set155_tab2" class="tab-label" data-tab-name="2"><p>Доступ к профилю ограничен</p></label><input type="radio" name="tab_radio_155" id="set155_tab3" class="tab-radio"><label for="set155_tab3" class="tab-label" data-tab-name="3"><p>Доступ ограничен. Пройдите проверку по лицу</p></label><div class="tab-panels"><div class="tab-panel"><img src="https://www.avito.ru/files/helpcenter/New%20hc/Profile/blocked/profile_blocked_screen_1.png" alt="Экран «Профиль заблокирован»"><p>Фраза под <strong>Профиль заблокирован</strong> будет отличаться в зависимости от <a href="https://support.avito.ru/articles/3432">причины блокировки</a>.</p><div class="spoiler"><input type="checkbox" id="spoiler_468" class="spoiler-checker"><div class="spoiler-body"><div class="spoiler-title"><label class="spoiler-icon" for="spoiler_468"></label><div class="spoiler-text"><p>Узнать о причине блокировки</p></div></div><div class="spoiler-content"><p><a href="https://support.avito.ru/articles/3252">Ваши объявления могли вводить покупателей в заблуждение</a></p><p><a href="https://support.avito.ru/articles/2938?eventData%5BcontextId%5D=125">У вас есть другой профиль с пройденной проверкой</a></p><p><a href="https://support.avito.ru/articles/3253?eventData%5BcontextId%5D=125">Мы заметили в нём подозрительные признаки</a></p><p><a href="https://support.avito.ru/articles/1748?eventData%5BcontextId%5D=125">Несколько аккаунтов для размещения в одной категории</a></p><p><a href="https://support.avito.ru/articles/1749?eventData%5BcontextId%5D=125">Замечены признаки взлома</a></p><p><a href="https://support.avito.ru/articles/1750?eventData%5BcontextId%5D=125">Предлагали сомнительные условия сделок</a></p><p><a href="https://support.avito.ru/articles/1751?eventData%5BcontextId%5D=125">С профиля рассылали спам</a></p></div></div></div><p><strong>Что делать: </strong>посмотрите, что указано в оповещении:</p><ul><li><p>Если это «Мы заметили в нём признаки взлома» или «В нём замечены признаки взлома», <a href="https://support.avito.ru/request/713">напишите нам</a> — проверим, можно ли восстановить доступ.</p></li><li><p>Если есть кнопка «Пройти проверку», профиль можно восстановить. Но важно помнить, что пройти проверку можно только в одном профиле. Если вы уже проходили её в другом — <a href="https://support.avito.ru/articles/3048">свяжите профили</a>.</p></li><li><p>Другая причина или нет кнопки — восстановить профиль, скорее всего, не получится. Это значит, что мы заметили серьёзное нарушение <a href="https://www.avito.ru/legal/">правил</a>. Вы можете создать новый профиль — с новым номером телефона.</p><p><strong>Может быть полезно:</strong></p><p><a href="https://support.avito.ru/articles/3055">Что с заказами в заблокированном профиле</a></p><p><a href="https://support.avito.ru/articles/3432">Почему заблокировали профиль</a></p></li></ul></div><div class="tab-panel"><img src="https://www.avito.ru/files/helpcenter/New%20hc/Profile/access_profile_restricted_1.png" alt="Экран с предупреждением «Доступ к профилю ограничен»"><p><strong>Что делать: </strong>для начала нужно разобраться — у вас один профиль на Авито или несколько, а если несколько, есть ли доступ к другому профилю. Следуйте дальше в зависимости от ответа.</p><div class="spoiler"><input type="checkbox" id="spoiler_511" class="spoiler-checker"><div class="spoiler-body"><div class="spoiler-title"><label class="spoiler-icon" for="spoiler_511"></label><div class="spoiler-text"><p>У вас есть другой профиль и доступ к нему</p></div></div><div class="spoiler-content"><p>В этом случае вы можете <a href="https://support.avito.ru/articles/2334">связать профили</a>, чтобы вернуть доступ к заблокированному. Пароль и документы владельца в них будут общие, а объявления вы можете размещать разные.</p><p>Чтобы связать профили, нажмите <strong>Да, и с ним всё в порядке</strong> и следуйте инструкции.</p><p>Либо привяжите этот профиль из другого — активного. Вот как это сделать:</p><ul><li><p>с телефона: зайдите в Профиль и нажмите на «+» рядом со своим аватаром;</p></li><li><p>с компьютера: нажмите на стрелочку рядом с именем профиля и в самом низу нажмите на «+» рядом с вашим аватаром.</p><div class="factoid factoid_important"><p>Не привязывайте профили других людей — даже если это ваши родственники, друзья или коллеги. Оба профиля должны принадлежать вам.</p></div></li></ul><p>Если активный профиль не подтверждён, мы попросим <a href="https://support.avito.ru/articles/2324?eventData%5BcontextId%5D=125">подтвердить</a> его перед связкой.</p><p>После привязки один из профилей станет <a href="https://support.avito.ru/articles/2685">профессиональным</a> — его можно красиво оформить, чтобы привлечь больше внимания к объявлениям и выделиться среди конкурентов. Перейти на профессиональный профиль можно бесплатно.</p></div></div></div><div class="spoiler"><input type="checkbox" id="spoiler_477" class="spoiler-checker"><div class="spoiler-body"><div class="spoiler-title"><label class="spoiler-icon" for="spoiler_477"></label><div class="spoiler-text"><p>У вас нет других профилей</p></div></div><div class="spoiler-content"><p>Тогда нужно пройти проверку. Выберите <strong>Нет, это единственный профиль</strong> и следуйте подсказкам. <br><br>Мы предложим пройти проверку по паспорту или правам, а юрлицам и ИП — по реквизитам. Доступные способы вы увидите на экране.<br><br>⚡ Пожалуйста, постарайтесь вспомнить, что у вас точно нет другого профиля, в котором вы подтверждали свои данные — даже удалённого или того, в который вы давно не заходили. Проходить проверку повторно нельзя — иначе профиль заблокируют.</p></div></div></div><div class="spoiler"><input type="checkbox" id="spoiler_866" class="spoiler-checker"><div class="spoiler-body"><div class="spoiler-title"><label class="spoiler-icon" for="spoiler_866"></label><div class="spoiler-text"><p>Другой профиль есть, но доступа к нему нет</p></div></div><div class="spoiler-content"><p>Выберите <strong>Есть, но я не могу им пользоваться</strong>. А дальше важно понять — проходили ли вы в старом профиле проверку по видео, документам, личному кабинету в банке или как-нибудь ещё.</p><ul><li><p>Если проверки не было — пройдите её в новом заблокированном профиле. Нажмите <strong>К проверке</strong> и следуйте подсказкам на экране.</p></li><li><p>Если в старом профиле была пройдена проверка, в новом её проходить нельзя — иначе мы заблокируем новый профиль и воспользоваться им не получится. Нужно <a href="https://support.avito.ru/articles/1795">восстановить старый профиль</a> и <a href="https://support.avito.ru/articles/2334">связать его с текущим</a>.</p><img src="https://www.avito.ru/files/helpcenter/New%20hc/Profile/blocked/profile_get_access_way_1.png" alt="Как вернуть доступ к профилю"></li></ul></div></div></div></div><div class="tab-panel"><img src="https://www.avito.ru/files/helpcenter/New%20hc/Profile/access_profile_restricted_2.png" alt="Экран с предупреждением «Доступ ограничен. Пройдите проверку по лицу»"><p>Если видите такое сообщение, достаточно показать своё лицо на камеру, чтобы вернуть доступ к профилю.</p><p><strong>Вот несколько важных советов:</strong></p><ul><li><p>снимайте себя при хорошем освещении на нейтральном фоне, например, у однотонной светлой стены;</p></li><li><p>не надевайте головные уборы и очки, если их нет на фото в паспорте;</p></li><li><p>не закрывайте лицо волосами, масками и другими предметами;</p></li><li><p>убедитесь, что в кадр не попадают другие люди;</p></li><li><p>смотрите прямо в камеру;</p></li><li><p>проверьте, что лицо попадает в рамку на экране.</p></li></ul></div></div></div>'